### ISSUE TITLE
Refactor manual-linking.sh to use external configuration file

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/Setup-Mac#6]
## Description
Currently, the `manual-linking.sh` script has all the file paths hardcoded in the script itself. This makes it difficult to maintain and extend as the number of configuration files grows.

## Proposed Changes
Refactor the script to use a separate configuration file (YAML or JSON) that defines all the symbolic links to be created. This would:

1. Separate configuration from code
2. Make it easier to add new files without modifying the script
3. Allow for more metadata about each link (e.g., description, category)

### 1. Create a configuration file (e.g., `links.yaml`):
```yaml
links:
  # Shell configurations
  - source: dotfiles/.bash_profile
    target: ~/.bash_profile
    category: shell
    description: Bash profile configuration
  
  - source: dotfiles/.bashrc
    target: ~/.bashrc
    category: shell
    description: Bash runtime configuration
  
  # Nix configurations
  - source: dotfiles/nix/core.nix
    target: /etc/nix-darwin/core.nix
    category: nix
    description: Nix core configuration
    requires_sudo: true
  
  # ... other links
  
  # Nushell configurations
  - source: dotfiles/.config/nushell/config.nu
    target: ~/.config/nushell/config.nu
    category: nushell
    description: Nushell configuration
    ensure_parent_dir: true
  
  - source: dotfiles/.config/nushell/config.nu
    target: ~/Library/Application Support/nushell/config.nu
    category: nushell
    description: Nushell configuration (Application Support)
    ensure_parent_dir: true
```

### 2. Update the script to use this configuration:
```bash
#!/bin/bash

# Check if yq is installed (for YAML parsing)
if ! command -v yq &> /dev/null; then
    echo "Error: yq is required but not installed. Please install it first."
    echo "You can install it with: brew install yq"
    exit 1
fi

CURRENT_DIR=$(pwd)
CONFIG_FILE="$CURRENT_DIR/links.yaml"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file not found at $CONFIG_FILE"
    exit 1
fi

verified_link() {
    local source="$1"
    local target="$2"
    local requires_sudo="$3"
    local ensure_parent_dir="$4"
    
    # Expand the source path if it's relative
    if [[ ! "$source" = /* ]]; then
        source="$CURRENT_DIR/$source"
    fi
    
    # Expand the target path if it contains ~
    target="${target/#\~/$HOME}"
    
    # Ensure parent directory exists if requested
    if [ "$ensure_parent_dir" = "true" ]; then
        parent_dir=$(dirname "$target")
        mkdir -p "$parent_dir"
    fi
    
    # Check if target already exists
    if [ -L "$target" ]; then
        current_source=$(readlink "$target")
        if [ "$current_source" != "$source" ]; then
            echo "Warning: Symbolic link at $target points to $current_source instead of $source"
            read -p "Do you want to replace it? (y/n) " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                if [ "$requires_sudo" = "true" ]; then
                    sudo rm "$target"
                    sudo ln -s "$source" "$target"
                else
                    rm "$target"
                    ln -s "$source" "$target"
                fi
                echo "Symbolic link updated to point to $source"
            else
                echo "Keeping existing symbolic link"
            fi
        else
            echo "Symbolic link at $target correctly points to $source"
        fi
    elif [ -e "$target" ]; then
        echo "Error: A file or directory exists at $target but it is not a symbolic link"
    else
        echo "Creating symbolic link from $source to $target"
        if [ "$requires_sudo" = "true" ]; then
            sudo ln -s "$source" "$target"
        else
            ln -s "$source" "$target"
        fi
    fi
}

# Process all links from the configuration file
NUM_LINKS=$(yq '.links | length' "$CONFIG_FILE")

for ((i=0; i<$NUM_LINKS; i++)); do
    source=$(yq ".links[$i].source" "$CONFIG_FILE")
    target=$(yq ".links[$i].target" "$CONFIG_FILE")
    category=$(yq ".links[$i].category" "$CONFIG_FILE")
    requires_sudo=$(yq ".links[$i].requires_sudo // false" "$CONFIG_FILE")
    ensure_parent_dir=$(yq ".links[$i].ensure_parent_dir // false" "$CONFIG_FILE")
    
    echo "Processing [$category] $source -> $target"
    verified_link "$source" "$target" "$requires_sudo" "$ensure_parent_dir"
done

echo "All symbolic links have been processed."
```

## Benefits
- Improved maintainability by separating configuration from code
- Easier to add new files without modifying the script
- Better organization with categories and descriptions
- More flexible with additional metadata for each link
- Ability to selectively process links by category

## Dependencies
- Requires `yq` for YAML parsing (or `jq` if using JSON)
